In [1]:
# IMPORTS -------------------------------------------------------------------- #
import os
import sys
from pathlib import Path
import re

import matplotlib.pyplot as plt
from matplotlib import rcParams
import numpy as np
import pandas as pd
import seaborn as sns

import utils

workspace,experiment=utils.workspace()
from __future__ import annotations

sys.path = [p for p in sys.path if "positron-python" not in p]

import anndata as ad
import scanpy as sc

In [2]:
sc.settings.verbosity = 3  # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.set_figure_params(dpi=80, facecolor="white")
sc.logging.print_header()

matplotlib	3.11.1
numpy	2.5.2
pandas	3.0.5
seaborn	0.13.2
anndata	0.13.2
scanpy	1.12.3
----	----
pexpect	4.9.0
traitlets	5.16.1 (5.15.1)
kiwisolver	1.5.0
executing	2.2.1
typing_extensions	4.16.0
tornado	6.5.7
legacy-api-wrap	1.5
pure_eval	0.2.3
donfig	0.8.1.post1
platformdirs	4.11.0 (4.4.0)
Pygments	2.20.0
scverse-misc	0.1.3
setuptools	83.0.0
wcwidth	0.8.2 (0.8.1)
pydantic-settings	2.14.2
stack_data	0.6.3
pyarrow	25.0.1
google-crc32c	1.8.0
threadpoolctl	3.6.0
msgpack	1.2.1
annotated-types	0.8.0
numcodecs	0.16.5
pydantic	2.13.4
debugpy	1.8.21
fonttools	4.63.0
parso	0.8.7
jedi	0.20.0 (0.19.2)
typing-inspection	0.4.2
fsspec	2024.6.1
asttokens	3.0.2
joblib	1.5.3
patsy	1.0.2
packaging	26.2
narwhals	2.24.0
statsmodels	0.14.6
comm	0.2.3
session-info2	0.4.2
matplotlib-inline	0.2.2
psutil	7.2.2
ptyprocess	0.7.0
scipy	1.18.0
llvmlite	0.49.0
pyzmq	27.1.0
six	1.17.0
pillow	12.3.0
ipywidgets	8.1.9
cycler	0.12.1
ipython	9.16.1 (8.18.1)
python-dateutil	2.9.0.post0
ipykernel	7.3.0 (6.31.0)
numba	0.67.0
h5py	3.16.0
natsort	8.4.0
fast-array-utils	1.5
prompt_toolkit	3.0.53 (3.0.52)
jupyter_core	5.9.1 (5.8.1)
zarr	3.3.0
pyparsing	3.3.2
jupyter_client	8.9.1 (8.6.3)
python-dotenv	1.2.2
PyYAML	6.0.3
scikit-learn	1.9.0
pydantic_core	2.46.4
charset-normalizer	3.5.1
----	----
Python	3.14.6 | packaged by conda-forge | (main, Aug 11 2026, 10:26:15) [GCC 14.4.0]
OS	Linux-6.1.0-53-amd64-x86_64-with-glibc2.36
CPU	256/256 logical CPU cores
GPU	No GPU found
Updated	2026-09-24 13:19

In [3]:
# PATHS ---------------------------------------------------------------------- #
results_file = workspace/'data/pbmc3k.h5ad'
read_file=workspace/'data/PBMC3k/filtered_gene_bc_matrices/hg19'
result_dir=experiment/'results'
assert read_file.exists()

In [4]:
# READ 10X-GENOMICS-FORMATTED MTX DIRECTORY ---------------------------------- #
# path: Path to directory for .mtx and .tsv files
# var_names: the variables index (options from genes.tsv file: 'gene_symbols', 'gene_ids')
# make_unique: Whether to make the variables index unique by appending ‘-1’, ‘-2’ etc. or not.
# cache: If False, read from source, if True, read from fast ‘h5ad’ cache.
# ---------------------------------------------------------------------------- #
genes=pd.read_csv(read_file/'genes.tsv',sep='\t',header=None).rename(columns={0:'gene_ids',1:'gene_symbols'})
adata = sc.read_10x_mtx(
    path=read_file,
    var_names='gene_symbols', #  # use gene symbols for the variable names (variables-axis index)
    make_unique=True, # make gene symbols unique
    cache=True, # write a cache file for faster subsequent reading
    )
adata.write(result_dir/'pbmc3k_raw.h5ad')
adata

... reading from cache file cache/omics-odcf-analysis-OE0290_projects-heroes-aya_pools-AG_Thongjuea-Code-10x_multiomics-Selina-project-data-PBMC3k-filtered_gene_bc_matrices-hg19-matrix.h5ad

AnnData object with n_obs × n_vars = 2700 × 32738
    var: 'gene_ids'
    layers: None (.X)

In [5]:
adata.var

                     gene_ids
MIR1302-10    ENSG00000243485
FAM138A       ENSG00000237613
OR4F5         ENSG00000186092
RP11-34P13.7  ENSG00000238009
RP11-34P13.8  ENSG00000239945
...                       ...
AC145205.1    ENSG00000215635
BAGE5         ENSG00000268590
CU459201.1    ENSG00000251180
AC002321.2    ENSG00000215616
AC002321.1    ENSG00000215611

[32738 rows x 1 columns]

In [6]:
new_genes = list(set([re.sub(r'-.','',gene) for gene in adata.var[~adata.var.index.isin(genes.gene_symbols)].index]))
len(new_genes)

91

In [7]:
# DUPLICATE GENE SYMBOLS ----------------------------------------------------- #
# during read_10x_mtx, some gene_symbols are already recognized as duplicates
# they receive an appendage: U1 -> [U1, U1-1]
# ---------------------------------------------------------------------------- #

print(adata.var.index.duplicated().sum()) # if 0 no adata.var_names_make_unique() necessary

dupl = [idx.replace('-1','') for idx in adata.var.index if idx.endswith('-1') and idx.replace('-1','') in adata.var.index]
genes_duplicated = genes[genes.gene_symbols.duplicated()].drop_duplicates(subset=['gene_symbols'])
genes_duplicated.shape, len(dupl)

pd_dupl = pd.DataFrame([{'symbol':gene,'genes':genes.query('gene_symbols==@gene').shape[0],'adata':adata.var.reset_index(names='gene_symbols').query('gene_symbols==@gene').shape[0]} for gene in dupl])
pd_dupl

0

     symbol  genes  adata
0        U1      2      1
1     EFNA3      2      1
2     DCAF8      2      1
3    MRPL30      2      1
4     LIMS3      2      1
..      ...    ...    ...
86    ZNF84      2      1
87    ZNF26      2      1
88  KIR3DL2      2      1
89    PNRC2      2      1
90   SRSF10      2      1

[91 rows x 3 columns]

# QC metrics

In [8]:
# DEFINE GENES --------------------------------------------------------------- #
# mitochondrial genes
genes_mt = adata.var_names.str.startswith("MT-")
adata.var["mt"] = genes_mt
# ribosomal genes
genes_ribo = adata.var_names.str.startswith(("RPCS","RPL"))
adata.var["ribo"] = genes_ribo
# hemoglobin genes.
genes_hb = adata.var_names.str.contains(r"^HB[ABDEGMQZ]\d*(?!\w)")
adata.var["hb"] = genes_hb
sum(genes_mt),sum(genes_ribo),sum(genes_hb)

(np.int64(13), np.int64(56), np.int64(10))